[package]
name = "seq"
version = "0.1.0"
authors = ["beltegeuse <adrien.gruson@gmail.com>"]
edition = "2018"

[dependencies]
gnuplot = "*"
rand = "*"
bencher = "*"

[[bench]]
name = "example"
harness = false